src/NewsBundle/Extension/Entity/Secure.php
<?php

namespace NewsBundle\Extension\Entity;

/**
 * @author Rosana Pencheva <rossana.russeva@gmail.com>
 */
trait Secure
{

    /**
     * Generate secure of ID
     * 
     * @return string
     */
    public function getSecureId()
    {
        $className = get_class($this);
        $className = str_replace('Proxies\__CG__', null, $className);

        return call_user_func("{$className}Repository::secure", $this->id);
    }

    /**
     * Make hash sign of secure ID
     * 
     * @return string
     */
    public function getHashSecureId()
    {
        $hashSecureId = substr(md5($this->getSecureId()), 0, 8);
        return $hashSecureId;
    }

}

src/NewsBundle/Form/NewsType.php
<?php

namespace NewsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use KMS\FroalaEditorBundle\Form\Type\FroalaEditorType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use NewsBundle\Form\FilesType;

/**
 * Description of NewsType
 *
 * @author Rosana Pencheva <rossana.russeva@gmail.com>
 */
class NewsType extends AbstractType {

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add(
                        'title', TextType::class, [
                    'attr' => ['class' => 'form-control']
                        ]
                )
                ->add(
                        'text', FroalaEditorType::class, []
                )
                ->add(
                        'date', DateType::class, [
                    'widget' => 'single_text',
                    'attr' => ['class' => 'js-datepicker form-control'],
                    'html5' => false,
                        ]
                )
                 ->add('files', CollectionType::class,array(
                    'entry_type' => FilesType::class,
                    'allow_add' => true,
                    'by_reference' => false,
                     'label' => " "
                ))
                ->add('active', CheckboxType::class, array(
                    'label' => 'Active',
                    'attr' => ['class' => ' mx-auto'],
                ))
                
                ->add(
                        'create', SubmitType::class, [
                    'attr' => ['class' => 'btn btn-primary pull-right'],
                    'label' => 'Save'
                        ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => 'NewsBundle\Entity\NewsPost',
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
            'validation_groups' => array('news_post'),
            'dataTags' => []
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getName() {
        return 'news_form';
    }

}

src/NewsBundle/Controller/NewsController.php
<?php

namespace NewsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use NewsBundle\Form\NewsType;
use NewsBundle\Entity\NewsPost;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Symfony\Component\HttpFoundation\Response;

/**
 * 
 *
 * @author  Rosana Pencheva <rossana.russeva@gmail.com>
 * 
 * @Security("has_role('ROLE_USER')")
 * 
 */
class NewsController extends Controller {

    /**
     * @Route("/news", name="news_homepage")
     * @Template()
     */
    public function indexAction(Request $request) {
        $user = $this->getUser();
        $query = $this->getDoctrine()
                ->getRepository('NewsBundle:NewsPost')
                ->createQueryBuilder('t')
                ->leftJoin('t.createdBy', 'c')
                ->where('c.id=:userId')
                ->setParameter('userId', $user->getId())
                ->orderBy('t.date', 'DESC')
                ->getQuery()
        ;
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $query, $request->get('page', 1), 25
        );
        return [
            'pagination' => $pagination
        ];
    }

    /**
     * @Route("/create/news", name="news_create")
     * @Template()
     */
    public function createAction(Request $request) {
        $newsPost = new NewsPost();

        $form = $this->createForm(NewsType::class, $newsPost);
        $form->handleRequest($request);

        // Check is valid
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $newsPost->setCreatedBy($this->getUser());
            //multiple files
            $attachments = $newsPost->getFiles();
            if ($attachments) {
                foreach ($attachments as $attachment) {
                    $file = $attachment->getFile();

                    // var_dump($attachment);
                    $filename = md5(uniqid()) . '.' . $file->guessExtension();

                    $file->move(
                            $this->getParameter('upload_path'), $filename
                    );
                    $filename = '../upload/' . $filename;
                    $attachment->setFile($filename);
                    $em->persist($attachment);
                }
            }

            $em->persist($newsPost);
            $em->flush($newsPost);

            $this->addFlash('success', 'Congratulations! Your post is created');

            $url = $this->generateUrl('news_homepage');

            return $this->redirect($url);
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route("/publish/{id}/news", name="news_publish")
     * @Method("GET")
     */
    public function publishAction(Request $request, $id) {
        $newsPost = $this->getDoctrine()
                ->getRepository('NewsBundle:NewsPost')
                ->findOneBySecureId($id);
        if ($newsPost) {
            $newsPost->setActive(true);
            $em = $this->getDoctrine()->getManager();
            $em->persist($newsPost);
            $em->flush($newsPost);
            $this->addFlash('success', 'Congratulations! Your post is published');
        }
        $url = $this->generateUrl('news_homepage');
        return $this->redirect($url);
    }

    /**
     * @Route("/delete/{id}/news", name="news_delete")
     * @Method("GET")
     */
    public function deleteAction(Request $request, $id) {
        $newsPost = $this->getDoctrine()
                ->getRepository('NewsBundle:NewsPost')
                ->findOneBySecureId($id);
        if ($newsPost) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($newsPost);
            $em->flush($newsPost);
            $this->addFlash('success', 'Your post is deleted!');
        }
        $url = $this->generateUrl('news_homepage');
        return $this->redirect($url);
    }

    /**
     * @Route("/download/{id}/news", name="news_download")
     * @Method("GET")
     */
    public function pdfAction(Request $request, $id) {
        $post = $this->getDoctrine()
                ->getRepository('NewsBundle:NewsPost')
                ->findOneBySecureId($id);
        if ($post) {
            $html = $this->renderView('NewsBundle:frontend:pdf.html.twig', array(
                'post' => $post,
                'base_dir' => $this->get('kernel')->getRootDir() . '/../web' . $request->getBasePath()
            ));

            $filename = $post->getTitle() . date("YmdHs") . '.pdf';

            return new Response(
                    $this->get('knp_snappy.pdf')->getOutputFromHtml($html), 200, array(
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"'
                    )
            );
        } else {
            $this->addFlash('success', 'The news does not exist!');
            $url = $this->generateUrl('news_homepage');
            return $this->redirect($url);
        }
    }

}

src/NewsBundle/Resources/views/news/_form.html.twig
{{ form_row(form.title) }}
{{ form_row(form.text) }}
{{ form_label(form.date) }}
{{ form_widget(form.date) }}   
{{ form_label(form.files) }}
<ul class="files" data-prototype="{{ form_widget(form.files.vars.prototype)|e('html_attr') }}">
    {% for element in form.files %}
        <li>
            {{ form_widget(element.file) }}
        </li>
    {% endfor %}
</ul>
{{ form_widget(form.active) }}
{{ form_label(form.active) }}
{{ form_row(form.create) }}

src/NewsBundle/Resources/views/news/create.html.twig
{% extends '@News/Layout/layout.html.twig' %}

{% block title %} {{ 'Create'|trans }} {% endblock %}

{% block body %}

    <div class="container">
        <section class="panel">
            <div class="panel-body">
              
                <div class="row">
                    <div class="col-md-6 offset-md-6">
                        <h3>Create news post</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 offset-md-6">
                        {{ form_start(form,{heading: 'New', 'attr': {'novalidate': 'novalidate'} }) }}
                        
                        {% include 'NewsBundle:news:_form.html.twig' %}
                        
                      
                        {{ form_rest(form, {offsetClass: ' '}) }}
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %} 

src/NewsBundle/Resources/views/news/index.html.twig
{% extends '@News/Layout/layout.html.twig' %}

{% block title %} {{ 'News'|trans }} {% endblock %}

{% block body %}
   
    <div class="container">
        <section class="panel">            
            <div class="panel-body">
               
                <div class="row">
                    <div class="col-md-6 offset-md-6">
                        <h3>{{ 'Your news' }}</h3>
                        <a class="btn btn-primary" href="{{ path('news_create') }}">{{ 'New' }}</a>
                        <!--Table-->              
                        <table class="table table-striped table-condensed">  
                            <!--Table head-->
                            <thead>
                                <tr>         
                                    <th class="th-lg">Actions</th>
                                    <th class="th-lg">Title</th>
                                    <th class="th-lg">Date</th>
                                    <th class="th-lg">Active</th>
                                </tr>
                            </thead>
                            <!--Table head-->
                            <!--Table body-->
                            <tbody>
                                {% for post in pagination %}
                                    <tr>
                                        <td>
                                            <a href="{{path('news_publish', {'id': post.secureId})}}" class="btn btn-sm btn-default">{{'Publish'}}</a>
                                            <a href="{{path('news_delete', {'id': post.secureId})}}" class="btn btn-sm btn-default">{{'Delete'}}</a>
                                        </td>
                                        <td><a href="{{path('frontend_show_post', {'id': post.secureId})}}">{{ post.title }}</a></td>
                                        <td>{{ post.date|date('d-m-Y') }}</td>
                                        <td>{% if post.active == 1 %}{{ 'Published' }}{% else %}{{ 'Unpublished' }}{% endif %}</td>
                                        
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <!--Table body-->
                        </table>
                        <div class="pagination container">
                            {{ knp_pagination_render(pagination) }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %} 